public class InventoryModel {

    public String seller; //null,
    public String stockFactor; //null,
    public String externalWarehouseId; //null,
    public String availableAdjusted; //0,
    // public String _id; //"60fa93b7780e4ff72618b5a8",
    public String sku; //"1000037152018778",

    public StoreInfo storeId;

    public String appliedFactor; //0,
    public String available; //0,
    public String createdAt; //"2021-07-23T10:02:31.617Z",
    public String description; //"PIJAMA MALWEE LIBERTA 1000037152 - 7498 - 8",
    public String notIntegratedOnOrder; //0,
    public String origin; //"Millennium",
    public String queryDate; //"2021-08-06T10:45:28.252Z",
    public String queryMethod; //"delta",
    public String reserved; //0,
    public String status; //"done",
    public String storeCode; //"IFC",
    public String total; //0,
    public String updatedAt; //"2021-08-07T07:54:08.555Z"

    public class StoreInfo {
        // public String _id; // "5bd10dd619c52b0027ad29a5",
        public String code; // "IFC",
        public String description; // "Loja teste VTEX -> MLN Infracommerce",
        public String icon; // "https://assets.website-files.com/60625f8508d07c3d896ed5a1/60ad38f7ee5237e42f3094ee_infracommerce-32x32-.png",
        public String name; // "Infracommerce",
        public String siteUrl; // "https://infracommerce.vtexcommercestable.com.br/"
    }

    public InventoryModel (){}
}